### ISSUE TITLE
🦺[Tech Debt] Offer dynamic fee rates

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#13]
## Description
Currently the Android and iOS clients query the the API server for fee rates.  

## Problem
The fees are static and the Litewallet Mobile API server should serve up the freshest LTC fee rates

## Background
While the server has and end-point for fees, the clients use an onboard value

**In iOS:**
```
fileprivate let defaultEconomyFeePerKB: UInt64 = 2500 // From legacy minimum. default min is 1000 as Litecoin Core version v0.17.1 
fileprivate let defaultRegularFeePerKB: UInt64 = 25000
fileprivate let defaultLuxuryFeePerKB: UInt64 = 66746
```

While the server has the endpoint:
```
app.get("/fee-per-kb", (req, res) => {
  res.json({
    fee_per_kb: 10000,
    fee_per_kb_economy: 2500
  });
});
```

## Goals

- [ ] Update lookup in the `litewallet-mobile-api` server from a dynamic source like [Bitinfocharts Fees](https://bitinfocharts.com/comparison/litecoin-transactionfees.html)
- [ ] Refactor the api server endpoint
- [ ] Refactor Android Client lookup query
- [ ] Refactor iOS Client lookup query
- [ ] Run Tests in Beta Android
- [ ] Run Tests in Beta iOS

**Comment by losh11** [comment]
The hardcoded fees are supposed to be just fallback incase the api server
becomes unreachable. This is because SPV clients have no way to telling how
full blocks are.

**Comment by kcw-grunt** [comment]
@losh11 that makes sense.  This work is so that the api server _may_ fresh rates.  currently, its never checked.
