### ISSUE TITLE
New Welcome Animation

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#17]
## Story
The current experience for users is sparse and most need background information prior to using Litewallet. Despite the instructions in the installation, most people (technical or not) get confused and have panic episodes regarding Litewallet. **This is a big problem.**

## Goals
We need to a better job of educating our users so they are fully informed and understand what Litewallet does.

## Subtasks 
- [ ] Develop a new design for the Welcome Animation 
- [ ] Implement the design in Android : [New Animation: Android Issue](https://github.com/litecoin-foundation/loafwallet-ios/issues/233)
- [ ] Implement the design in iOS : [New Animation: IOS Issue](https://github.com/litecoin-foundation/loafwallet-android/issues/232)
- [ ] Iterate after user feedback
- [ ] Add to Android an iOS releases

**Comment by kcw-grunt** [comment]
@antematijaca  
Thanks for your offer of help!  This is the main ticket/issue and there are the supporting tickets in bullet 2 and 3..
