### ISSUE TITLE
🥳[Feature] Add Moonpay to Litewallet

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#19]
## Goal
Add Moonpay to the Android and iOS clients so users have options to buy Litecoin in Litewallet

## Tasks
- [x] Add Moonpay backend API
- [x] Add Moonpay to Litewallet iOS
- [x] Add Moonpay to Litewallet Android 

## Clip
|Proposed Action|
|----------------|
|![moonpay.gif](https://images.zenhubusercontent.com/5f8eddb90548c55f1ee6e011/fe9db188-ff83-463c-b2c1-81262e2056f1)|
