### ISSUE TITLE
🥳[Feature] Add Changenow to Litewallet

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#31]
## Goal
Add [ChangeNow](https://changenow.io) to the Android and iOS clients so users have options to `exchange` Litecoin in Litewallet

## Tasks
- [ ] Add ChangeNow backend API
- [ ] Add ChangeNow to Litewallet iOS
- [ ] Add ChangeNow to Litewallet Android 

## Clip
|Proposed Action|
