### ISSUE TITLE
[ Tech Debt ] Automate the upload of App Store and Play Store Metadata

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#6]
## Goal
Scale upload of the app metadata so the team don't have to manually upload the localizations and the marketing data

## Approach
Each store has different methods. But the overall architecture needs to be followed:

1. Get API Access 
 - [ ] Android :  [Play Store API Access](https://play.google.com/console/u/1/developers/4847849587992708188/api-access)
 - [ ] iOS :  [App Store API Access](https://appstoreconnect.apple.com/access/api)

2. Follow the schema for updating the metadata 
- [ ] Android : 
- [ ] iOS :  app-store-connect-openapi-spec.json

3. Configure an environment for updating the metdata. When release is ready, the test and steps must allow pass/fail.  These steps may be
 - Localization of all text in the change
 - Update Locales (for instance Spanish (ES) and Spanish (MX) and Spanish (Ven)
 - Update the release notes with localizations
 - Update the screenshots and the video clips

4. A web app that can manage this data can be created to inject with the release or it can be integrated into the codebase

## Supporting Issues

- [ ] Automate upload of App Store Metadata **ADD IOS ISSUE HERE**
- [ ] Automate upload of Play Store Metadata  **ADD ANDROID ISSUE HERE**
